// Function returns a license badge based on which license is passed in
// If there is no license, return an empty string
function renderLicenseBadge(license) {
     if (license !== "None") {
       return `![Badge](https://img.shields.io/badge/License-${license}-blue.svg)`
     }
     return ``;
   }
   
   // Function returns the license link
   // If there is no license, return an empty string
   function renderLicenseLink(license) {
     if (license !== "None") {
       return `- [License](#license)`
     }
     return ``;
   }
   
   // Function returns the license section of README
   // If there is no license, return an empty string
   function renderLicenseSection(license) {
     if (license !== "None") {
       return `## License
       This application is covered by the ${license} license.`
     }
     return ``;
   
   }
   
   // Function to generate markdown for README
   function generateMarkdown(data) {
     return `
     
   # Title
     ${data.title}

   ## Description
     ${data.description}
   
   ## Table of Content
   - [Installation](#installation)
   - [Usage](#usage)
   - [Contribution](#contribution)
   ${renderLicenseLink(data.license)}
   - [Test](#Test)
   
   ## Installation
     ${data.installation}
   
   ## Usage
     ${data.usage}
     
   ## Contribution
     ${data.contribution}
   
   ## License 
     ${renderLicenseSection(data.license)}
     
   ## License Badge
   
   ${renderLicenseBadge(data.license)}

   
   ## Test
     ${data.test}
   
   ## Contact
   Email me at: ${data.email} 
     
   GitHub: ${data.github} 
     
   ## Copyright
   
     README generated by hkhalfan
   `;
   }
   
   module.exports = generateMarkdown;